### ISSUE TITLE
Create HTML block

### ISSUE THREAD

**Issue by herzog31** [hlxsites/maidenform#140]
- [x] Create block that includes HTML fragments
- [x] HTML fragments will be in GitHub
- [x] Add a reference
- [x] Ensure security (maybe CSP?)
- [x] Support for loading JS in <script> tags (including inline code)
- [x] Add example and present in weekly sync
- [x] Add support for fragments from branches whose name includes "/"
- [x] Add support for locally hosted fragments

### Phase 2
- [x] Decide on block configuration options
    - We need to be able to display content within a date range
    - There should be a fallback if no date range is matching the current date
- [x] Add scheduling functionality to the block
- Preview functionality to be added via #232

**Comment by hannessolo** [comment]
Putting these 2 code snippets here for inspiration - I think we can reuse parts:
- Code to fetch and display external html: https://github.com/hlxsites/maidenform/blob/e5486ae1f223c07842d4a3e01bb9a33fd7e8cfe9/blocks/product-details/ProductDetails.js#L35
- https://github.com/hlxsites/maidenform/blob/main/blocks/fragment/fragment.js

**Comment by herzog31** [comment]
Re-open since phase 2 is still open.
