### ISSUE TITLE
Dynamic breadcrumb for PDP

### ISSUE THREAD

**Issue by herzog31** [hlxsites/maidenform#142]
- [ ] Breadcrumb on PDP should be loaded dynamically via GraphQL to show the correct path
- [ ] Breadcrumb block should not be the first block on the page to ensure the PDP block is the first one and an LCP block

**Comment by hannessolo** [comment]
TODO: Many products have several categories. We need to either remove all the excess categories or make sure we can add a field that selects the canonical category.
