### ISSUE TITLE
Move Promo Banner Block in Header or Auto Blocking

### ISSUE THREAD

**Issue by herzog31** [hlxsites/maidenform#147]
- [x] The promo banner block should not be the first block on the homepage. This should be the HTML block, to ensure it's the LCP block.
- [x] Since the promo banner is only visible on the homepage, it could be added via auto blocking. 
- [x] Use page metadata to define if the promo banner should be displayed or not.

**Comment by herzog31** [comment]
@karigaron17 The promo banner block is now part of the HTML block. Is this something you would like to keep this way or are you open that we move this to a separate block which will be added automatically, e.g. through some page metadata field.

**Comment by karigaron17** [comment]
I started a branch to move to a separate block, just have not had time to finish it yet. Not 100% sure about the adding part, other then was planning on it being a block in word with the files in the blocks folder that get pulled if used.

**Comment by herzog31** [comment]
Related to #278

**Comment by Kronnox** [comment]
@karigaron17 Are you still actively working on this? Otherwise I could take over. I'm sort of blocked with #278 by this, depending on the implementation

**Comment by karigaron17** [comment]
I am not actively working on this no. If it is blocking then by all means go for it. I was not working on moving it, had made it part of the htlm snippet for scheduling reasons on the last hp content build. But wanted to move it to a block.
