### ISSUE TITLE
[PWA] Cart

### ISSUE THREAD

**Issue by herzog31** [hlxsites/maidenform#187]
- [x] Dedicated cart page
- [x] Edit configurable product functionality

![SCR-20230412-d71](https://user-images.githubusercontent.com/4084418/231385050-76c5dce3-38f6-4737-be83-11403cf752ca.png)

Out of scope: #189

**Comment by fe-lix-** [comment]
Moving this item `Enable share-able links that apply coupon codes` to its own ticket #263

**Comment by fe-lix-** [comment]
With the modification of scope this ticket can now be closed.
