### ISSUE TITLE
[PWA] ReCaptchaV3 configuration

### ISSUE THREAD

**Issue by herzog31** [hlxsites/maidenform#202]
* For ReCaptchaV3 to work properly, the following conditions have to be met:
    - [x] Package installed: https://github.com/magento/magento2-pwa/tree/main/ReCaptchaGraphQlPwa (GraphQL API)
    - [ ] Package installed: https://github.com/magento/magento2-pwa/tree/main/ReCaptchaPwa (server-side validation?)
    - [x] ReCaptchaV3 (Invisible) configured in Magento Admin according to https://developer.adobe.com/commerce/webapi/graphql/usage/protected-mutations/
    - [x] ReCaptcha query returns proper values:
    ```graphql
  {
      recaptchaV3Config {
          website_key
          badge_position
          language_code
          forms
      }
  }
    ```
* Current issues that need to be fixed:
    - [x] ReCaptcha configuration does not allow usage of `localhost` or `127.0.0.1`
    - [x] GraphQL query returns null on stage and QA environments.
    - [x] With hardcoded captcha configuration (same values as configuration in Magento admin), the captcha is properly generated on the frontend, but the server-side validation fails.

On our test instance, we installed the `magento/pwa` and `magento/pwa-commerce` meta packages and the captcha GraphQL query returned proper values. However the full meta packages should not be required, since only the two packages mentioned above include parts relevant to captchas.

**Comment by Jordaneisenburger** [comment]
I've configured the QA enviornment to show a RecaptchaV3 for the edit account form and it seems to be working. 
For now I've just configured some test credentials via my personal account, this needs to be changed by Hanes. Let me know if you need further assistance on this matter.

![Screenshot 2023-05-02 at 10 09 02](https://user-images.githubusercontent.com/19858728/235616877-d1636098-4ccc-4da4-bcc2-251b136e2b6e.png)

**Comment by herzog31** [comment]
@jokiser see the comment above. Recaptcha V3 is now configured on the QA environment and properly picked up by PWA Studio. Could your team please ensure to have the same available on Stage as well? I'm not sure why it works just like this on QA and didn't work on Stage when we tried it together. @Jordaneisenburger said he didn't have to do anything special.
