### ISSUE TITLE
Add Commerce Patch B2B-2598 and Update Settings

### ISSUE THREAD

**Issue by herzog31** [hlxsites/maidenform#225]
* See https://experienceleague.adobe.com/tools/commerce-quality-patches/index.html, search for `B2B-2598`
* The improves performance of frequently used GraphQL queries.
    > Add caching capability to the availableStores, countries, country, currency, and storeConfig GraphQL queries
* [x] Install patch B2B-2598
* [x] If on 2.4.5 (and higher), disable GraphQL sessions via `bin/Magento config:set graphql/session/disable 1` for an additional boost in performance for GraphQL APIs

**Comment by jacobhanesbowman** [comment]
@attila-sagi-born completed the installation for Patch B2B-2598 yesterday morning. @herzog31 Could you confirm that this is working as expected?

**Comment by jokiser** [comment]
Hi @hannessolo / @mhaack, this patch is now on our stage environment and should be available for validation. Is there any way to confirm this is working as expected?

CC: @jacobhanesbowman

**Comment by hannessolo** [comment]
Closing for now. I don't have the context for this, and don't know how to verify.

Perhaps @herzog31 can help.
