### ISSUE TITLE
Product Recommendations - Out-of-stock products showing

### ISSUE THREAD

**Issue by jokiser** [hlxsites/maidenform#237]
(Similar to https://github.com/hlxsites/maidenform/issues/229)

Noticed in the product recommendations widget that some out-of-stock products are showing.

Steps to Reproduce:
- Navigate to franklin.maidenform.com (homepage) or any PDP (e.g. https://franklin.maidenform.com/products/dm2301/DM2301) and scroll down to the product recommendations section

Expected Results:
- All products shown in the recommendations widget should be "in stock" products

Actual Results:
- "Out of stock" products are sometimes shown in the recommendations widget
  - Notice the product with a broken / missing image (see screenshot below)
  - This is product DM7546 which is flagged in the Magento DB as "out of stock"

Screenshot of a recommendations widget with a broken / missing image, for an "out-of-stock" product (DM7546):
![image](https://user-images.githubusercontent.com/12847422/234050411-b5cb19b7-32ea-45ef-8a5c-1683c4157fa7.png)

Screenshot of the same product (DM7546) in Magento admin, indicating it is flagged as "out of stock":
![image](https://user-images.githubusercontent.com/12847422/234050908-44c47f51-e913-4470-aba8-219f61325862.png)

**Comment by herzog31** [comment]
Be aware that the displayed recommendations are not final. We should display recommendations as configured in Magento for specific pages (e.g. homepage, PDP, etc.). In these configurations you can define what type of recommendation it is (e.g. most viewed products) and any additional filters (e.g. not out of stock products).

**Comment by herzog31** [comment]
@aniham do you have an idea how we could filter out products that are not in stock? See my "hack-ish" solution in #275 which assumes that out of stock products do not have a proper price assigned.

**Comment by aniham** [comment]
@herzog31 yes - so the way to do this is through admin config which i don't believe we've gotten to yet with maidenform. there is a configuration option there that excludes out of stock items from api response:

![Screen Shot 2023-05-11 at 8 42 30 AM](https://github.com/hlxsites/maidenform/assets/847621/5e4e1a94-b938-4bfb-bb5d-66cd65090b7d)

**Comment by herzog31** [comment]
Filter in API should look like this:

```
"filterRules": [
  {
    "name": "Exclusion rules",
    "type": "Exclusion",
    "conditions": [
      {
        "field": "outOfStock",
        "operatorType": "isOperator",
        "operator": {
          "isOperator": {
            "type": "is",
            "value": true
          }
        },
        "enabled": true
      }
    ]
  }
]
```
