### ISSUE TITLE
Manage Category Disruptors in Excel

### ISSUE THREAD

**Issue by herzog31** [hlxsites/maidenform#245]
This is an idea how to replace Amasty for managing category disruptors as defined in #135 with Franklin.

- [x] Manage images/banners for disruptors in Sharepoint.
- [x] Create an Excel file with columns like:
    - Date from
    - Date to
    - Name
    - Link
    - Path to image
    - Position (offset of product positions)
    - Size (1-4 product positions)
    - All Pages? (on which page to display the disruptor, only first or all)
    - Category ID (select via Commerce picker)
- [x] PDP block will read this configuration and display a disruptor if one is available for a given category at a given date.

**Things to be figured out:**
  - [ ] ~~How to display disruptors in a way to not add additional or incomplete rows.~~
  - [x] Load them in a way so they don't cause layout shift.

**Comment by Kronnox** [comment]
A disruptor size of `>2` doesn't really make sense, as the grid will have rows with only two columns on mobile. Setting a size greater than the column amount will glitch out the grid.
