### ISSUE TITLE
Wrong image showing for first product card in listing (after interacting with color swatches)

### ISSUE THREAD

**Issue by jokiser** [hlxsites/maidenform#252]
Noticed after interacting color swatches and thereafter filters / facets and / or pagination that the wrong product image will occasionally show for product cards in the listing.

Steps to reproduce:
- Navigate to a PLP or search page (e.g. https://franklin.maidenform.com/lounge)
- Expand the color family facet to view options
- Click the "red" color swatch
- Observe the listing update based on selection
- For the first product card, change the color swatch (e.g. click the "red" swatch)
- Notice the image refresh accordingly
- Deselect the color family filter

Expected results:
- The listing is refreshed and the product image of the first card accurately reflects the respective product

Actual results:
- The listing is refreshed and the product image of the first card does not reflect the respective product (wrong image is shown)

---

Listing after selecting "red" color family from the filter / facets and changing the color swatch of the first product:
![image](https://user-images.githubusercontent.com/12847422/235563235-f8d262bf-b5a3-497d-a9fd-a37fb61ce16a.png)

Listing of the same page after deselecting the color family filter / facet option (notice the wrong product image is showing for the first product):
![image](https://user-images.githubusercontent.com/12847422/235563688-2217f899-ae53-4b70-989f-e81825936036.png)

**Comment by jokiser** [comment]
This is not isolated to facets / filters nor is it isolated to the first product card.

Alternate steps to reproduce:
- Navigate to a PLP or search listing page (e.g. https://franklin.maidenform.com/lounge)
- Change the color swatch of the first and second products
- Click via pagination controls to view page 2
- Notice the first two product images are wrong (neither belongs to the respective product)

![image](https://user-images.githubusercontent.com/12847422/235564178-f1097aa4-fd91-4851-aaf9-e0f675956b61.png)

![image](https://user-images.githubusercontent.com/12847422/235564296-438a18a9-19fd-4f3c-b784-ac16af4f62cc.png)

**Comment by jacobhanesbowman** [comment]
This issue is no longer reproducible on main. Tested in Microsoft Edge v112 Desktop. Evidence attached:
![dashboard](https://user-images.githubusercontent.com/131693166/236001174-562aba9c-fafc-4ef2-b764-27fca972fdca.gif)
