### ISSUE TITLE
Previewing nav edits via draft folder file 

### ISSUE THREAD

**Issue by karigaron17** [hlxsites/maidenform#258]
Need the ability to make edits to the nav.doc that can be previewed via any /drafts url.
If there is a nav.doc located in the drafts folder that version of the doc is used and shown. This can be used for testing new navigation items and for setting up adding or removing navigation items.
Nav changes can then be scheduled using power automate to replace the default nav doc with the drafts doc as needed.

**Comment by herzog31** [comment]
@karigaron17 Could you please review https://github.com/hlxsites/maidenform/pull/264 and check if this works for you?
