### ISSUE TITLE
 Share-able links that apply coupon codes

### ISSUE THREAD

**Issue by fe-lix-** [hlxsites/maidenform#263]
- [x] Enable share-able links that apply coupon codes
- [x] Logic on every page that looks for `y1` query parameters and stores them in a cookie.
- [x] Cart &
- [x]  checkout can read the cookie, apply the coupon and delete the cookie.
- [x] Include `d1` logic as per https://stage.maidenform.com/static/frontend/Magento/base/default/Born_MarketingChannel/js/marketingchannel.min.js
- [ ] Track `d1` value in ACDL.

**Comment by herzog31** [comment]
@jokiser could you please add some more details to this use case?

**Comment by jokiser** [comment]
Note: We need to make sure these types of links work for category pages as well.

Here's a live example (URL to bras category / department page):
https://www.maidenform.com/bras.html?d1=EMAIL&utm_source=MFB&utm_medium=EMAIL&utm_campaign=Trigger_MFB_Welcome_T1_AsOf-2022-06-16&utm_term=WELCOMET1&utm_content=20230511&y1=MWS9Q8L0&bt_ee=wwd3BsT2gCG%2F7cQHlVqK1liCPWEwrqkNmdGqEIUahA2XAFi3UvFKsM8LNeFAr5634rq8%2BKCaHo5clixHrR6STg%3D%3D&bt_ts=1683809000962

**Comment by herzog31** [comment]
@jokiser you mentioned that the logic should respect both `y1` and `d1` values. In the URL you shared, `d1=EMAIL` and `y1=MWS9Q8L0`. But I assume only `y1` is the correct coupon value right?

**Comment by herzog31** [comment]
Okay, so we apply `y1` as coupon and can track `d1` via ACDL.

**Comment by dicagno** [comment]
@jokiser do we have a fixed format for the coupon code, that we can use to test the input param?

**Comment by hannessolo** [comment]
@aniham will provide documentation how to implement the custom event in ACDL

**Comment by dicagno** [comment]
@hannessolo shall we merge this one and create an issue for ACDL integration? wdy?

**Comment by hannessolo** [comment]
> @hannessolo shall we merge this one and create an issue for ACDL integration? wdy?

Let's see if Neela can help us implement it today, if not we can merge it and open a separate issue.
