### ISSUE TITLE
Update footer banner to match prod behavior

### ISSUE THREAD

**Issue by jokiser** [hlxsites/maidenform#288]
Noticed the banner in franklin.maidenform.com is rotating much more quickly (~4s) compared to production (~5s) and does not pause on hover. Need to update the behavior to reflect how it operates in production.

Behavior on franklin.maidenform.com (notice it rotates upon hover):
![chrome-capture-2023-4-17](https://github.com/hlxsites/maidenform/assets/12847422/d5cef97b-c7d4-4da9-a4bc-4b5d7e651fab)

**Comment by amit-c1308** [comment]
Hey, just checked the footer banner code.
Seems like the animation is already on an interval of 3 secs in code and even on hover the banner carousel keeps going.
Has this been addressed already ?

**Comment by jokiser** [comment]
Checked again just now and it does appear the rotation is much slower now (which looks great!). However, the animation still does not pause on hover. Considering this a lower priority at this time now that the speed issue has been addressed.
