### ISSUE TITLE
Wrap ® in <sup> tag

### ISSUE THREAD

**Issue by karigaron17** [hlxsites/maidenform#290]
Need to wrap the ® in the product title on the PLP, PDP and in the breadcrumbs in <sup> tag.
Inner html is pulled from database so need to check if ® is present then add the <sup>®</sup> around it and add back to the existing inner html.

Note: on PLP needs to keep the <sup> when/if a filter option is applied to the page.

**Comment by Aryan123-rgb** [comment]
I would like to work on this

**Comment by karigaron17** [comment]
> I would like to work on this

By all means go for it.
