### ISSUE TITLE
Versioning mechanism for static assets such as JS and CSS

### ISSUE THREAD

**Issue by jokiser** [hlxsites/maidenform#296]
It appears there is no versioning mechanism in place for JS and / or CSS files; Upon merging changes in such files to ```main```, we're noticing caching issues which will present a variety of challenges.

Is there any way we can implement a versioning mechanism such that updates to CSS and JS files will force clients to download the latest version?

**Comment by hannessolo** [comment]
Could you describe this in more detail? This shouldn't be an issue. Are you still experiencing this?

Franklin uses push invalidation to clear the cache. https://www.hlx.live/docs/byo-cdn-fastly-setup#setup-push-invalidation

**Comment by jokiser** [comment]
Note for historical reference: Looks like we encountered this issue again this morning following the push of the cart updates to ```main```. I could not get the cart page to render (was getting 404s repeatedly as a result of being directed to /cart/checkout). Only way I could get around this was to flush my local browser cache (which most of our consumers would not know how to do*).

*If in the future there is an urgency issue we need to fix for our consumers and we need to push a JS file or CSS update to fix, I'm worried we'll not be able to force invalidation of these files for our consumers (and as a result they'd be stuck with the issue until TTL expires).
