### ISSUE TITLE
My Account Page is broken

### ISSUE THREAD

**Issue by fe-lix-** [hlxsites/maidenform#358]
My Account Page is empty after sign in.

**Comment by hannessolo** [comment]
Which branch is this on? I can't reproduce this on issue/188.
![Screenshot 2023-06-22 at 20 18 17](https://github.com/hlxsites/maidenform/assets/24207564/6dd720c5-9426-4126-9119-858a19c417cc)

**Comment by herzog31** [comment]
I fixed this in https://github.com/hlxsites/maidenform/pull/276/commits/7983e9d9e47912a50c66b4f0887f390a1f94289a
