### ISSUE TITLE
CDN setup

### ISSUE THREAD

**Issue by herzog31** [hlxsites/maidenform#4]
- [x] Customer to define which CDN they want to use
    - Currently using Fastly, long term probably Akamai
- [x] Reach out to Adobe Commerce customer support to get credentials needed for Franklin Fastly setup. https://experienceleague.adobe.com/docs/commerce-knowledge-base/kb/help-center-guide/magento-help-center-user-guide.html?lang=en#submit-ticket
- [x] Setup Fastly with development subdomain
    - [x] Follow https://www.hlx.live/docs/byo-cdn-fastly-setup
    - e.g. `franklin.maidenform.com`
    - [x] Setup `.helix/config.xlsx` configuration once auth token is available.
    - [x] It looks like Fastly is pointing to `https://main--maidenform--hlxsites.hlx.page` instead of `https://main--maidenform--hlxsites.hlx.live` which causes content in preview stage to appear on `franklin.maidenform.com`.
- [x] Setup proxy (VCL) or Compute@Edge for the following integrations
    - [x] Proxy Monolith Commerce GraphQL endpoint
         - [x] Make sure correct CORS headers are set, so the endpoint can be in all required contexts (sharepoint, hlx.page/.live, etc.)
         - CORS example: https://developer.fastly.com/solutions/examples/cors-options-preflights-at-the-edge
         - Rewrite example: https://developer.fastly.com/solutions/examples/rewrite-url-path
         - e.g. `franklin.maidenform.com/graphql`
         - to be decided if catalog service endpoint should be proxied as well
         - [x] All requests (`GET` + `POST`) to `franklin.maidenform.com/graphql` should return `Access-Control-Allow-Origin` header.
             - https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS/Errors/CORSMissingAllowOrigin
             - Verify with `curl -v -o /dev/null -H "Origin: https://main--maidenform--hlxsites.hlx.page" https://franklin.maidenform.com/graphql`. Should return `access-control-allow-origin: https://main--maidenform--hlxsites.hlx.page` header.
    - ~~[x] _TBD_ DAM integration (#17)~~
    - [ ] _TBD_ Side-by-side integration for cart page, checkout and myaccount (#14, #15, #16)
- [ ] ~~**ALTERNATIVE:** Update CDN configuration of https://stage.maidenform.com/graphql to send correct CORS headers so it can be used by client-side blocks.~~

**Comment by herzog31** [comment]
Waiting for Commerce support to setup Fastly with Franklin.

**Comment by herzog31** [comment]
Waiting for Adobe Commerce support to provide Fastly token, so Franklin CDN configuration can be applied.

Also waiting for Maidenform team to setup proxy for `/graphql` endpoint.

**Comment by shherman** [comment]
@herzog31 if you need help for Fastly Token Access and Commerce Cloud please ping Geetha Ramamoorthy gramamoorthy@adobe.com and myself on slack and we will work to assist you.

**Comment by herzog31** [comment]
While testing the CORS setup, I found that only parts of the required origins are supported. You can test this with the following command:

```bash
curl -Is -H "Origin: https://franklin.maidenform.com" https://franklin.maidenform.com/graphql | grep "access-control-allow-origin"
```

| Origin | Value of `access-control-allow-origin` | Behavior |
| ------ | --------------------------------------- | -------- |
| https://franklin.maidenform.com | `invalid-origin` | 🔴  |
| https://main--maidenform--hlxsites.hlx.live | `https://main--maidenform--hlxsites.hlx.live` | 🟢  |
| https://main--maidenform--hlxsites.hlx.page | `https://main--maidenform--hlxsites.hlx.page` | 🟢  |
| https://issue-6--maidenform--hlxsites.hlx.page | `invalid-origin` | 🔴 |
