### ISSUE TITLE
mstyle Page

### ISSUE THREAD

**Issue by herzog31** [hlxsites/maidenform#44]
- [x] https://www.maidenform.com/mstyle -> https://main--maidenform--hlxsites.hlx.page/mstyle
- [ ] Add links to images

**Comment by kmurugulla** [comment]
https://main--maidenform--hlxsites.hlx.page/mstyle - created the content page . It is 90% visually accurate to the live site except the the first picture which is a label stacking on to the second one. Once this page is reviewed by the customer team a decision should be made to add any styling or just leave it as it is now.

**Comment by herzog31** [comment]
@kmurugulla the page looks good. I think we don't need special styles for it.

The images however are missing links like on the original page. That's something we need to add.
