### ISSUE TITLE
Style simple content pages

### ISSUE THREAD

**Issue by herzog31** [hlxsites/maidenform#5]
- [x] Add styles and blogs for the following content pages
    - [ ] https://www.maidenform.com/customer-service
    - [ ] https://www.maidenform.com/privacy-policy
    - [ ] https://www.maidenform.com/secure-shopping
    - [ ] https://www.maidenform.com/accessibility
    - [ ] https://www.maidenform.com/terms-of-use

**Comment by kmurugulla** [comment]
@herzog31 - Please review the pull request #34
